# Generated by Django 5.0.6 on 2024-06-26 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaFullstackApp', '0002_producto_created_producto_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categorias',
        ),
        migrations.DeleteModel(
            name='CategoriaProd',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
